### ISSUE TITLE
Add-on no longer functions

### ISSUE THREAD

**Issue by MartijnKaijser** [Trippel-M/plugin.video.fatstone#1]
I get an error opening the plugin
https://paste.ubuntu.com/p/nFZtC3FqHk/

I have marked the add-on broken in the Kodi repo for now.

**Comment by haakonnessjoen** [comment]
This will be fixed on monday. I’m sorry for the inconvinience

**Comment by MartijnKaijser** [comment]
Np. Thx 👍

**Comment by MartijnKaijser** [comment]
I bumped the version so take that in account that you bump it +2

**Comment by haakonnessjoen** [comment]
the problem is serverside though. I don't need to do anything with the module.

In fact, it should be working again now.

**Comment by haakonnessjoen** [comment]
Could you please test it, and unmark it, if it works?

**Comment by MartijnKaijser** [comment]
Bumped it to not broken. Not tested though
